name: CI Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')


  unit_test:
    runs-on: ubuntu-latest
    container: python:3.12
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python and dependencies
        run: |
          python --version
          pip install -e .[dev]

      - name: Run unit tests
        run: python -m unittest discover

  deploy:
    runs-on: ubuntu-latest
    container: python:3.12
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python and dependencies
        run: |
          python --version
          pip install -e .[dev]

      - name: Generate rule list
        run: bibla list-all -m | python -m markdown -x tables > all_rules.html
        if: github.ref == 'refs/heads/master'

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: all-rules
          path: all_rules.html
