image: "python:3.10"  # Changed to a more stable version

before_script:
  - python --version
  - pip install --upgrade pip setuptools wheel  # Ensure latest tools
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -e .[dev]

stages:
  - Static Analysis
  - Test
  - Deploy

flake8:
  stage: Static Analysis
  script:
    - mkdir out
    - flake8 --append-config .flake8 | tee out/lint_result.txt
    - num_warnings=$(wc -l < out/lint_result.txt)
    - cat out/lint_result.txt
    - echo "$num_warnings warnings!"
    - anybadge -v=$num_warnings -f=out/flake8.svg -l=flake8 10=green 1000=orange 10000=red
    - if [ $num_warnings -gt 0 ]; then exit 1; fi
  artifacts:
    when: always
    paths:
      - out/flake8.svg
      - out/lint_result.txt
  allow_failure: true

unit_test:
  stage: Test
  script:
    - python -m unittest discover

rule_list:
  stage: Deploy
  script:
    - bibla list-all -m | python -m markdown -x tables > all_rules.html
  only:
    - master
  artifacts:
    paths:
      - all_rules.html
