# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]
  push:
    branches:
      - master

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install markdown

      - name: Build package
        run: python -m build

      - name: Install built package
        run: pip install dist/*.whl 

      - name: Publish package to pip
        if: github.event_name == 'release'
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Generate rule list
        run: |
          bibla list-all -m | python -m markdown -x tables > all_rules.html

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "Pipeline"
          git config --global user.email "pipeline@no.one"
          git clone --single-branch --branch pages https://github.com/mrclassict/bibla pages
          cat docs/rulesTemplate.md all_rules.html > docs/rules.md
          git add docs/rules.md
          git commit -m "Add/update rules.md page"
          git push https://${{secrets.BIBLA_GITHUB_TOKEN}}@github.com/mrclassict/bibla.git

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: all-rules
          path: docs/rules.md
